//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebClient.HelloWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWebService.HelloWebserviceSoap")]
    public interface HelloWebserviceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMesaage", ReplyAction="*")]
        HelloWebClient.HelloWebService.GetMesaageResponse GetMesaage(HelloWebClient.HelloWebService.GetMesaageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMesaage", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWebClient.HelloWebService.GetMesaageResponse> GetMesaageAsync(HelloWebClient.HelloWebService.GetMesaageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMesaageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMesaage", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebClient.HelloWebService.GetMesaageRequestBody Body;
        
        public GetMesaageRequest() {
        }
        
        public GetMesaageRequest(HelloWebClient.HelloWebService.GetMesaageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMesaageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetMesaageRequestBody() {
        }
        
        public GetMesaageRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMesaageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMesaageResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebClient.HelloWebService.GetMesaageResponseBody Body;
        
        public GetMesaageResponse() {
        }
        
        public GetMesaageResponse(HelloWebClient.HelloWebService.GetMesaageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMesaageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMesaageResult;
        
        public GetMesaageResponseBody() {
        }
        
        public GetMesaageResponseBody(string GetMesaageResult) {
            this.GetMesaageResult = GetMesaageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWebserviceSoapChannel : HelloWebClient.HelloWebService.HelloWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWebserviceSoapClient : System.ServiceModel.ClientBase<HelloWebClient.HelloWebService.HelloWebserviceSoap>, HelloWebClient.HelloWebService.HelloWebserviceSoap {
        
        public HelloWebserviceSoapClient() {
        }
        
        public HelloWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebClient.HelloWebService.GetMesaageResponse HelloWebClient.HelloWebService.HelloWebserviceSoap.GetMesaage(HelloWebClient.HelloWebService.GetMesaageRequest request) {
            return base.Channel.GetMesaage(request);
        }
        
        public string GetMesaage(string name) {
            HelloWebClient.HelloWebService.GetMesaageRequest inValue = new HelloWebClient.HelloWebService.GetMesaageRequest();
            inValue.Body = new HelloWebClient.HelloWebService.GetMesaageRequestBody();
            inValue.Body.name = name;
            HelloWebClient.HelloWebService.GetMesaageResponse retVal = ((HelloWebClient.HelloWebService.HelloWebserviceSoap)(this)).GetMesaage(inValue);
            return retVal.Body.GetMesaageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWebClient.HelloWebService.GetMesaageResponse> HelloWebClient.HelloWebService.HelloWebserviceSoap.GetMesaageAsync(HelloWebClient.HelloWebService.GetMesaageRequest request) {
            return base.Channel.GetMesaageAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWebClient.HelloWebService.GetMesaageResponse> GetMesaageAsync(string name) {
            HelloWebClient.HelloWebService.GetMesaageRequest inValue = new HelloWebClient.HelloWebService.GetMesaageRequest();
            inValue.Body = new HelloWebClient.HelloWebService.GetMesaageRequestBody();
            inValue.Body.name = name;
            return ((HelloWebClient.HelloWebService.HelloWebserviceSoap)(this)).GetMesaageAsync(inValue);
        }
    }
}
